image: gradle:alpine

default:
  tags:
    - shell_local

stages:
  - run tests

Run tests:
  stage: run tests
  script:
    - ./gradlew clean test -D "selenide.headless=true"
    - ./gradlew allureReport
  artifacts:
    paths:
      - build/reports/allure-report/allureReport/*